#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_1/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_2/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_matexpl_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_matexpl_params_maxitscg_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_maxitscg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4b/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_maxitscg_warmed_up_flame.svg


