#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case0/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_cg_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_cg_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_cg_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_cg_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_4/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_cg_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_cg_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_cg_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_cg_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_5/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_cg_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_cg_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_cg_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_cg_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_global_matfree_cg_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case0/trafo_none/order_6/cells_2/hybridization_global_matfree_cg_warmed_up_flame.svg


