#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case1/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/hybridization_lu_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/gtmg_matexpl_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/gtmg_matexpl_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/gtmg_matexpl_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_0/cells_2/gtmg_matexpl_params_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/hybridization_lu_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/gtmg_matexpl_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/gtmg_matexpl_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/gtmg_matexpl_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_1/cells_2/gtmg_matexpl_params_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/hybridization_lu_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/gtmg_matexpl_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/gtmg_matexpl_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/gtmg_matexpl_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_2/cells_2/gtmg_matexpl_params_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/hybridization_lu_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/gtmg_matexpl_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/gtmg_matexpl_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/gtmg_matexpl_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_3/cells_2/gtmg_matexpl_params_warmed_up_flame.svg
mkdir -p flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/hybridization_lu_params_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/gtmg_matexpl_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/gtmg_matexpl_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/gtmg_matexpl_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case1/trafo_none/order_4/cells_2/gtmg_matexpl_params_warmed_up_flame.svg


