#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_fully_matfree_params_matexpmg_assembledjacobi_fs0_cg_jacobi_fgmres_evenlesstolonS_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_fully_matfree_params_matexpmg_assembledjacobi_fs0_cg_jacobi_fgmres_evenlesstolonS_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_fully_matfree_params_matexpmg_assembledjacobi_fs0_cg_jacobi_fgmres_evenlesstolonS_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case5aa/trafo_none/order_4/cells_3/gtmg_fully_matfree_params_matexpmg_assembledjacobi_fs0_cg_jacobi_fgmres_evenlesstolonS_warmed_up_flame.svg


