#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case6a/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_outerfgmres_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_outerfgmres_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_outerfgmres_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_outerfgmres_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/hybridization_lu_params_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/hybridization_lu_params_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/hybridization_lu_params_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6a/trafo_none/order_3/cells_3/hybridization_lu_params_warmed_up_flame.svg


