#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case6/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_matexpl_nested_schur_params_fgmres_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_matexpl_nested_schur_params_fgmres_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_matexpl_nested_schur_params_fgmres_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_matexpl_nested_schur_params_fgmres_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case6/trafo_none/order_0/cells_3/gtmg_fully_matfree_params_fs0_cg_jacobi_fs1_cg_laplacian_jacobi_fgmres_warmed_up_flame.svg


