#!/bin/sh
mkdir -p ./svgs/flames/mixed_poisson/pplus1pow3//case4e/trafo_none/
cd svgs
mkdir -p flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_global_matfree_params_matexpmg_assembledjacobi_fgmres_warmed_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_fully_matfree_params_matexpmg_fgmres_assembledjacobi_warm_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_fully_matfree_params_matexpmg_fgmres_assembledjacobi_warm_up_flame.svg
curl https://raw.githubusercontent.com/sv2518/mathybperf/main/mathybperf/performance/flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_fully_matfree_params_matexpmg_fgmres_assembledjacobi_warmed_up_flame.svg>flames/mixed_poisson/pplus1pow3//case4e/trafo_none/order_5/cells_2/gtmg_fully_matfree_params_matexpmg_fgmres_assembledjacobi_warmed_up_flame.svg


